// constants/screenConstants.js

// Map backend screen IDs to frontend keys (upper snake case from description)
export const SCREEN_KEY_MAP = {
  'screen10': 'EMPLOYEE_LANDING_PAGE',
  'screen11': 'ONBOARD_NEW_EMPLOYEE_SKILL_TEST_TEACH',
  'screen12': 'ONBOARD_NEW_EMPLOYEE_NON_TEACH_BASIC_INFO_FORM',
  'screen13': 'ONBOARD_NEW_EMPLOYEE_NON_TEACH_ADDRESS_INFO_FORM',
  'screen14': 'ONBOARD_NEW_EMPLOYEE_NON_TEACH_FAMILY_INFO_FORM',
  'screen15': 'ONBOARD_NEW_EMPLOYEE_NON_TEACH_PREVIOUS_EMPLOYEE_INFO',
  'screen16': 'ONBOARD_NEW_EMPLOYEE_NON_TEACH_QUALIFICATION_FORM',
  'screen17': 'ONBOARD_NEW_EMPLOYEE_NON_TEACH_UPLOAD_DOCUMENTS_FORM',
  'screen18': 'ONBOARD_NEW_EMPLOYEE_NON_TEACH_CATEGORY_INFO_FORM',
  'screen19': 'ONBOARD_NEW_EMPLOYEE_NON_TEACH_BANK_INFO_FORM',
  'screen20': 'ONBOARD_NEW_EMPLOYEE_NON_TEACH_AGREEMENTS_FORMS',
  'screen21': 'ONBOARD_NEW_EMPLOYEE_NON_TEACH_SALARY_INFO_FORMS',
  'screen22': 'ONBOARDING_STATUS_TABLE_ONBOARDING_TABLE',
  'screen23': 'ONBOARDING_STATUS_TABLE_SKILL_TEST_TABLE',
  'screen24': 'ONBOARDING_STATUS_SKILL_TEST_PROFILE_CARD',
  'screen25': 'ONBOARDING_STATUS_DO_SCREENS_OVERVIEWS_WORKING_INFO',
  'screen26': 'ONBOARDING_STATUS_DO_SCREENS_OVERVIEWS_FAMILY_INFO',
  'screen27': 'ONBOARDING_STATUS_DO_SCREENS_OVERVIEWS_PREVIOUS_EMPLOYEE_INFO',
  'screen28': 'ONBOARDING_STATUS_DO_SCREENS_OVERVIEWS_QUALIFICATION_INFO',
  'screen29': 'ONBOARDING_STATUS_DO_SCREENS_OVERVIEWS_DOCUMENTS_INFO',
  'screen30': 'ONBOARDING_STATUS_DO_SCREENS_OVERVIEWS_CATEGORY',
  'screen31': 'ONBOARDING_STATUS_DO_SCREENS_OVERVIEWS_AGREEMENT',
  'screen32': 'ONBOARDING_STATUS_DO_SCREENS_OVERVIEWS_ACCOUNT_INFO',
  'screen33': 'ONBOARDING_STATUS_DO_SCREENS_OVERVIEWS_SALARY_INFO',
  'screen34': 'ONBOARDING_STATUS_DO_SCREENS_OVERVIEWS_CHECKLIST',
  'screen35': 'ONBOARDING_STATUS_CO_SCREENS_OVERVIEWS_WORKING_INFO',
  'screen36': 'ONBOARDING_STATUS_CO_SCREENS_OVERVIEWS_FAMILY_INFO',
  'screen37': 'ONBOARDING_STATUS_CO_SCREENS_OVERVIEWS_PREVIOUS_EMPLOYEE_INFO',
  'screen38': 'ONBOARDING_STATUS_CO_SCREENS_OVERVIEWS_QUALIFICATION_INFO',
  'screen39': 'ONBOARDING_STATUS_CO_SCREENS_OVERVIEWS_DOCUMENTS_INFO',
  'screen40': 'ONBOARDING_STATUS_CO_SCREENS_OVERVIEWS_CATEGORY',
  'screen41': 'ONBOARDING_STATUS_CO_SCREENS_OVERVIEWS_AGREEMENTS',
  'screen42': 'ONBOARDING_STATUS_CO_SCREENS_OVERVIEWS_ACCOUNT_INFO',
  'screen43': 'ONBOARDING_STATUS_CO_SCREENS_OVERVIEWS_SALARY_INFO_OVERVIEWS',
  'screen44': 'ONBOARDING_STATUS_CO_SCREENS_OVERVIEWS_CHECKLIST',
  // Add more if needed for empty rows, but ignore blanks for now
};

// Hierarchy for sub-tabs (parent paths with sub-screens)
export const TAB_SCREEN_MAPPING = {
  'hr-new-employee-onboarding': [
    'ONBOARD_NEW_EMPLOYEE_NON_TEACH_BASIC_INFO_FORM',
    'ONBOARD_NEW_EMPLOYEE_NON_TEACH_ADDRESS_INFO_FORM',
    'ONBOARD_NEW_EMPLOYEE_NON_TEACH_FAMILY_INFO_FORM',
    'ONBOARD_NEW_EMPLOYEE_NON_TEACH_PREVIOUS_EMPLOYEE_INFO',
    'ONBOARD_NEW_EMPLOYEE_NON_TEACH_QUALIFICATION_FORM',
    'ONBOARD_NEW_EMPLOYEE_NON_TEACH_UPLOAD_DOCUMENTS_FORM',
    'ONBOARD_NEW_EMPLOYEE_NON_TEACH_CATEGORY_INFO_FORM',
    'ONBOARD_NEW_EMPLOYEE_NON_TEACH_BANK_INFO_FORM',
    'ONBOARD_NEW_EMPLOYEE_NON_TEACH_AGREEMENTS_FORMS',
    'ONBOARD_NEW_EMPLOYEE_NON_TEACH_SALARY_INFO_FORMS',
  ],
  'hr-review': [
    'ONBOARDING_STATUS_TABLE_ONBOARDING_TABLE',
    'ONBOARDING_STATUS_TABLE_SKILL_TEST_TABLE',
    'ONBOARDING_STATUS_SKILL_TEST_PROFILE_CARD',
  ],
  'do-review': [
    'ONBOARDING_STATUS_DO_SCREENS_OVERVIEWS_WORKING_INFO',
    'ONBOARDING_STATUS_DO_SCREENS_OVERVIEWS_FAMILY_INFO',
    'ONBOARDING_STATUS_DO_SCREENS_OVERVIEWS_PREVIOUS_EMPLOYEE_INFO',
    'ONBOARDING_STATUS_DO_SCREENS_OVERVIEWS_QUALIFICATION_INFO',
    'ONBOARDING_STATUS_DO_SCREENS_OVERVIEWS_DOCUMENTS_INFO',
    'ONBOARDING_STATUS_DO_SCREENS_OVERVIEWS_CATEGORY',
    'ONBOARDING_STATUS_DO_SCREENS_OVERVIEWS_AGREEMENT',
    'ONBOARDING_STATUS_DO_SCREENS_OVERVIEWS_ACCOUNT_INFO',
    'ONBOARDING_STATUS_DO_SCREENS_OVERVIEWS_SALARY_INFO',
    'ONBOARDING_STATUS_DO_SCREENS_OVERVIEWS_CHECKLIST',
  ],
  'co-review': [
    'ONBOARDING_STATUS_CO_SCREENS_OVERVIEWS_WORKING_INFO',
    'ONBOARDING_STATUS_CO_SCREENS_OVERVIEWS_FAMILY_INFO',
    'ONBOARDING_STATUS_CO_SCREENS_OVERVIEWS_PREVIOUS_EMPLOYEE_INFO',
    'ONBOARDING_STATUS_CO_SCREENS_OVERVIEWS_QUALIFICATION_INFO',
    'ONBOARDING_STATUS_CO_SCREENS_OVERVIEWS_DOCUMENTS_INFO',
    'ONBOARDING_STATUS_CO_SCREENS_OVERVIEWS_CATEGORY',
    'ONBOARDING_STATUS_CO_SCREENS_OVERVIEWS_AGREEMENTS',
    'ONBOARDING_STATUS_CO_SCREENS_OVERVIEWS_ACCOUNT_INFO',
    'ONBOARDING_STATUS_CO_SCREENS_OVERVIEWS_SALARY_INFO_OVERVIEWS',
    'ONBOARDING_STATUS_CO_SCREENS_OVERVIEWS_CHECKLIST',
  ],
  // Add more hierarchies as per your app (e.g., profile-overview with subs)
  'profile-overview': [
    // From data, e.g., basic-info, family-info, qualificationDetails subs, etc.
    'POV_EMP_BASIC_INFO',
    'POV_EMP_FAMILY_ADDRESS_INFO',
    'POV_EMP_QUALIFICATION_DETAILS_BACHELORS',
    'POV_EMP_QUALIFICATION_DETAILS_INTERMEDIATE',
    'POV_EMP_QUALIFICATION_DETAILS_SCHOOLS',
    'POV_EMP_DOCUMENTS_SUBMITTED',
    'POV_EMP_DOCUMENTS_FILLED_FORMS',
    'POV_EMP_DOCUMENTS_ID_PROOFS',
    'POV_EMP_BANK_DETAILS',
    'POV_EMP_AGREEMENTS',
    'POV_EMP_SALARY_INFO',
  ],
  // Ignore blank screens for now
};

// Sample roles from data (for testing, backend will provide)
export const ROLES = [
  'Principal', 'CASHER', 'HR', 'DO', 'CO', 'Vice Principal', 'Jr HR', 'Hr Manager', 'AGM', 'Senior Lecturer', 'Dean'
];